
######################################################################
      # COLLECTION RUNS ON PUSH AND DAILY AT 07:00
######################################################################

name: Automated API tests using Postman CLI

on:
  push:
  schedule:
    - cron: "0 7 * * *"   # daily at 07:00 UTC

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

######################################################################
      # INSTALL AND LOGIN TO POSTMAN CLI + RUN AND UPLOAD TESTS
######################################################################

    steps:
      - uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests
        id: postman
        run: |
          postman collection run "17318486-52f1c847-da9f-4423-9c78-640fa2cdeed8" \
            --iteration-count 10 \
